import CodeBlock from "../components/CodeBlock/CodeBlock";

const ReduxToolkitEN = () => {
  return (
    <div className="article">
      <h1>Redux Toolkit – Complete Beginner Guide</h1>

      <h3>configureStore and installation</h3>
      <p>
        The <b>configureStore</b> automatically sets up Redux with a default
        configuration, including Redux DevTools, thunk middleware, and other
        essential tools. <br />
        <b>Installation:</b>
        <CodeBlock code={`npm install @reduxjs/toolkit react-redux`} />
      </p>
      <p>Let’s create a Redux store by providing a reducer object.</p>

      <CodeBlock
        code={`// store.js
import { configureStore } from "@redux/toolkit";
import { productReducer } from "./reducers";

const store = configureStore({
  reducer: {
    products: productReducer,
  },
});

export default store;`}
      />

      <h3>createSlice</h3>
      <p>
        The <b>createSlice</b> function is a utility that simplifies Redux logic
        by automatically generating action creators and reducer logic for a
        specific slice of the state.
      </p>

      <CodeBlock
        code={`// reducers.js
import { createSlice } from "@redux/toolkit";

const productSlice = createSlice({
  name: "products",
  initialState: {
    allProducts: [],
  },
  reducers: {
    addProduct: (state, action) => {
      state.allProducts.push(action.payload);
    },
    deleteProduct: (state, action) => {
      state.allProducts = state.allProducts.filter(
        (item) => item.id !== action.payload.id
      );
    },
  },
});

export const { addProduct, deleteProduct } = productSlice.actions;
export const productReducer = productSlice.reducer;`}
      />

      <p>
        In this example, <b>createSlice</b> defines a products slice and
        automatically generates the necessary actions and reducer.
      </p>

      <h3>How to use actions</h3>
      <p>
        To update the state, we use dispatch to send actions generated by
        createSlice.
      </p>

      <CodeBlock
        code={`// AddToCart.js
import React from "react";
import { useDispatch } from "react-redux";
import { addProduct } from "./reducers";

const AddToCart = ({ product }) => {
  const dispatch = useDispatch();

  const handleAddToCart = () => {
    dispatch(addProduct(product));
  };

  return (
    <button onClick={handleAddToCart}>
      🛒 Add to cart
    </button>
  );
};

export default AddToCart;`}
      />

      <CodeBlock
        code={`// ProductItem.js
import React from "react";
import AddToCart from "./AddToCart";

const ProductItem = () => {
  const product = {
    id: 1,
    name: "Phone",
  };

  return (
    <div>
      <h2>{product.name}</h2>
      <AddToCart product={product} />
    </div>
  );
};

export default ProductItem;`}
      />

      <h3>Connecting Redux to React</h3>

      <CodeBlock
        code={`// index.js
import React from "react";
import ReactDOM from "react-dom/client";
import { Provider } from "react-redux";
import App from "./App";
import store from "./store";

const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(
  <Provider store={store}>
    <App />
  </Provider>
);`}
      />

      <h3>Displaying products</h3>

      <CodeBlock
        code={`// for example in App.js
import React from "react";
import { useSelector } from "react-redux";

const App = () => {
  const products = useSelector((state) => state.products.allProducts);

  return (
    <div>
      <h1>Cart</h1>

      <ul>
        {products.map((item) => (
          <li key={item.id}>{item.name}</li>
        ))}
      </ul>
    </div>
  );
};

export default App;`}
      />

      <h3>folder structure for next.js</h3>
      <CodeBlock
        code={`src/
│
├── app/                  # routing (Next.js App Router)
│   ├── layout.js
│   ├── page.js
│   ├── products/
│   │   └── page.js
│   └── cart/
│       └── page.js
│
├── components/           # reusable UI components
│   ├── AddToCart.js
│   ├── ProductItem.js
│   └── CodeBlock.js
│
├── store/                # Redux Toolkit setup
│   ├── store.js
│   └── provider.js
│
├── features/             # feature-based Redux slices
│   └── products/
│       ├── productSlice.js
│       └── selectors.js
│
├── hooks/                # custom hooks
│   └── useAppDispatch.js
│
├── lib/                  # helpers / utils
   └── utils.js
`}
      />
    </div>
  );
};

export default ReduxToolkitEN;
